apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
  namespace: llm-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
        - name: chat-ui
          image: acrllmproyecto.azurecr.io/llm-project/chat-ui:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui
  namespace: llm-serving
spec:
  selector:
    app: chat-ui
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
